services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - my_volume:/app/instance # Map a writable volume for the instance folder
      - .:/app:ro # Keep the application code read-only for safety

volumes:
  my_volume:
