[tool.poetry]
name = "REST API project"
version = "0.1.0"
description = ""
authors = ["Emiliano Frigo"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pylint = "^2.17.4"
flask = ">=2.0.1"
pydantic = "^1.10.5"
flasgger = "^0.9.7.1"
